version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/${CH_DB_NAME}
      - QUARKUS_DATASOURCE_USERNAME=${CH_DB_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${CH_DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - connecthub-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${CH_DB_USER}
      POSTGRES_PASSWORD: ${CH_DB_PASSWORD}
      POSTGRES_DB: ${CH_DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt_BR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - connecthub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CH_USER} -d ${CH_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  connecthub-network:
    driver: bridge
